spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: food_ordering_app
    password: 12345
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database: oracle
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true

  sql:
    init:
      mode: always
      platform: oracle